# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
