# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_auto_20160204_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyToManyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ManyToManyField(related_name='many_to_many_book', to='author.Author')),
            ],
        ),
    ]
