# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_manytomanybook_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='author.Book')),
                ('year', models.PositiveIntegerField()),
            ],
            bases=('author.book',),
        ),
    ]
